spring:
   profiles:
      active: dev-6868
      
---
server:
   port: 6868
         
spring:
   profiles: dev-6868
   application:
      name: eureka-server
   security: 
      user: 
         name: navy
         password: 123456
   
eureka:
   instance: 
      hostname: localhost
   client:
      register-with-eureka: false # 如果要注册到集群中需要改成true
      fetch-registery: false
      serviceUrl:
         defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
   server:
         enable-self-preservation: false # 关闭自我保护
      
---
server:
   port: 6869
         
spring:
   profiles: dev-6869
   application:
      name: eureka-server
   security: 
      user: 
         name: navy
         password: 123456
   
eureka:
   instance: 
      hostname: localhost
   client:
      register-with-eureka: false # 如果要注册到集群中需要改成true
      fetch-registery: false
      serviceUrl:
         defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
   server:
         enable-self-preservation: false # 关闭自我保护